---

- name: Find cloud build file
  shell: |
    find /srv/www/*/x86_64/repos/*Cloud*/ -name build
  register: cloud_build_file

- name: Get media build version
  slurp:
    src: "{{ cloud_build_file.stdout }}"
  register: cloud_media_build_version
  failed_when: false
