---
- name: Setup repositories on the deployer node
  hosts: ardana-virt
  remote_user: root
  gather_facts: False

  pre_tasks:
    - name: Grow 1st partition filesystem
      shell: |
        /usr/sbin/growpart /dev/vda 1 && /sbin/resize2fs /dev/vda1
      ignore_errors: True

  roles:
    - setup_zypper_repos

  tasks:
    - name: Install ardana pattern
      zypper:
        name: "patterns-cloud-ardana"
        state: present

    # This can't happen earlier because we rely on the ardana pattern for creating
    # the ardana user/group
    - name: Ensure /etc/ardana exists
      file:
        path: /etc/ardana
        state: directory
        owner: ardana
        group: ardana

    - name: Capture build number of cloudsource media
      get_url:
        url: "{{ cloudsource_url }}/media.1/build"
        dest: /etc/ardana/media-build-version

    - name: Add build information to /etc/motd
      shell: |
        echo "Build job: {{ build_url }}" >>/etc/motd

    - name: Add cloudsource information to /etc/motd
      shell: |
        media_build_version=$(cat /etc/ardana/media-build-version)
        echo "Built from: {{ cloudsource_url }}" >>/etc/motd
        echo "Media build version: $media_build_version" >>/etc/motd

    - name: Add repos information to /etc/motd
      shell: |
        echo "Configured repositories: {{ repository_list|join(', ') }}" >>/etc/motd
      when: repositories != ''
