---

- name: Run cobbler-deploy
  command: |
    ansible-playbook -i hosts/localhost cobbler-deploy.yml \
      -e ardanauser_password='ardana'
  args:
    chdir: "{{ ardana_openstack_path }}"

- name: Get list of SLES nodes to reimage
  shell: 'cobbler profile list | grep "sles12sp3-x86_64-" | cut -d"-" -f3'
  become: yes
  register: ardana_sles_nodes

- name: Get list of RHEL nodes to reimage
  shell: 'cobbler profile list | grep "rhel73-x86_64-" | cut -d"-" -f3'
  become: yes
  register: ardana_rhel_nodes

- name: Run playbook to prepare SLES grub2
  command: |
    ansible-playbook -i hosts/localhost prepare-sles-grub2.yml \
      -e nodelist={{ ardana_sles_nodes.stdout_lines | join(',') }}
  args:
    chdir: "{{ ardana_openstack_path }}"

- name: Run playbook to prepare RHEL grub2
  command: |
    ansible-playbook -i hosts/localhost prepare-rhel-grub2.yml \
      -e nodelist={{ ardana_rhel_nodes.stdout_lines | join(',') }}
  args:
    chdir: "{{ ardana_openstack_path }}"
  when: ardana_rhel_nodes.stdout_lines | length

- name: Run playbook to reimage nodes
  command: |
    ansible-playbook -i hosts/localhost bm-reimage.yml \
      -e nodelist={{ (ardana_sles_nodes.stdout_lines + \
      ardana_rhel_nodes.stdout_lines) | join(',') }}
  args:
    chdir: "{{ ardana_openstack_path }}"
