---

- name: Configure ardana-extensions-ses
  lineinfile:
    path: "~/openstack/my_cloud/config/ses/settings.yml"
    regexp: "^ses_config_path:"
    line: "ses_config_path: /tmp/ses_config"
    insertbefore: "^ses_config_file:"
  register: ses_config

- name: Set default glance backend to RBD
  replace:
    dest: "~/openstack/my_cloud/definition/data/control_plane.yml"
    regexp: "(?<=-\\sglance-api)$"
    replace: ":\n                glance_default_store: 'rbd'"
  register: im

- name: Commit SES config changes
  shell: |
    git add -A
    git commit -m 'Add SES config'
  args:
    chdir: "{{ ardana_openstack_path }}"
  when: ses_config.changed or im.changed
