---

is_hw_env: "{{ inventory_hostname in groups['qe_all'] }}"

ardana_openstack_path: "~/openstack/ardana/ansible"
ardana_scratch_path: "~/scratch/ansible/next/ardana/ansible"

ardana_openstack_playbooks:
  - "config-processor-run.yml -e encrypt='' -e rekey=''"
  - "ready-deployment.yml"

ardana_scratch_playbooks:
  - play: "wipe_disks.yml -e automate=true"
    when: "{{ is_hw_env }}"
  - play: "site.yml"
  - play: "ardana-cloud-configure.yml"

ses_enabled: False
cloud_maint_updates_list: "{{ cloud_maint_updates.split(',') if cloud_maint_updates is defined and cloud_maint_updates | length else [] }}"
sles_maint_updates_list: "{{ sles_maint_updates.split(',') if sles_maint_updates is defined and sles_maint_updates | length else [] }}"
