---

- name: Ensure directories exists
  file:
    path: "{{ item.path | dirname }}"
    state: directory
  loop: "{{ jenkins_worker_copy_files }}"

- name: Copy files to new agent node
  copy:
    src: "{{ item.path }}"
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ jenkins_worker_copy_files }}"
  notify:
    - Restart jenkins swarm client
