---

- include_tasks: update.yml
- include_tasks: install_packages.yml
- include_tasks: configure_swarm_client.yml
- include_tasks: copy_files.yml
- include_tasks: setup_venv.yml
  when:
    - jenkins_worker_ansible_version is defined
    - jenkins_worker_ansible_version | length
- include_tasks: authorized_keys.yml
