---

- name: Generate Ardana Input Model
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    task: "deploy"

  pre_tasks:
    - include_role:
        name: rocketchat_notify
      vars:
        rc_action: "started"
        rc_state: "Started"
      when:
       - rc_notify
       - is_physical_deploy

  tasks:
    - block:
        - include_role:
            name: input_model_generator
      rescue:
        - include_role:
            name: rocketchat_notify
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."
      always:
        - include_role:
            name: jenkins_artifacts
          when: lookup("env", "WORKSPACE")
          vars:
            jenkins_artifacts_to_collect:
              - "{{ virt_config_file }}"
              - "{{ input_model_path }}"
