#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

tempest_log_url: "{{ lookup('env', 'BUILD_URL') }}artifact/.artifacts/testr_results_region1.log"

rc_announcement_started: "Running tempest {{ tempest_run_filter }}"
rc_announcement_finished: "{{ rc_previous_announcement.content | b64decode if rc_previous_announcement.content is defined else 'NA' }}"

rc_msg_fields_started:
  - title: Started by
    value: "{{ lookup('env', 'BUILD_URL') | default(lookup('env', 'USER'), true) }}"
    short: False
  - title: Deployer
    value: "{{ hostvars['ardana-' + qe_env].ansible_host }}"
    short: True
  - title: Filter
    value: "{{ tempest_run_filter }}"
    short: True
  - title: Ardana log stream
    value: "http://{{ hostvars['ardana-' + qe_env].ansible_host }}:9091/"
    short: True

rc_msg_fields_finished_temp:
  - title: Started by
    value: "{{ lookup('env', 'BUILD_URL') | default(lookup('env', 'USER'), true) }}"
    short: False
  - title: Deployer
    value: "{{ hostvars['ardana-' + qe_env].ansible_host }}"
    short: True
  - title: Filter
    value: "{{ tempest_run_filter }}"
    short: True
  - title: Ran
    value: "{{ tempest_results_processed.results.0.stdout if tempest_results_processed is defined else 'Not available' }}"
    short: True
  - title: Passed
    value: "{{ tempest_results_processed.results.1.stdout if tempest_results_processed is defined else 'Not available' }}"
    short: True
  - title: Skipped
    value: "{{ tempest_results_processed.results.2.stdout if tempest_results_processed is defined else 'Not available' }}"
    short: True
  - title: Failed
    value: "{{ tempest_results_processed.results.3.stdout if tempest_results_processed is defined else 'Not available' }}"
    short: True
  - title: Failed tests
    value: "{{ tempest_failed_tests.stdout if tempest_failed_tests is defined else 'Not available' }}"
    short: False
  - title: Tempest log
    value: "{{ tempest_log_url if lookup('env', 'BUILD_URL') else 'Not available' }}"
    short: False
  - title: OpenStack-Health
    value: "{{ os_health_url }}"
    short: False

rc_msg_fields_finished_defcore:
  - title: RefStack
    value: "{{ refstack_out.stdout if refstack_out is defined else 'Not available' }}"
    short: False

rc_msg_fields_finished: "{{ rc_msg_fields_finished_temp + rc_msg_fields_finished_defcore if tempest_run_filter == 'defcore' else rc_msg_fields_finished_temp }}"
